### ISSUE TITLE
Type 'ConstructNode' is missing the following properties from type 'Node': _locked, _children, _context, _metadata, and 6 more.

### ISSUE THREAD

**Issue by larrygoyeau** [aws-samples/aws-serverless-for-machine-learning-inference#2]
Hello

I'm running  ./cloud9_install.sh  on Cloud9 and I get the following error:

Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
253 packages excluded due to repository priority protections
Package jq-1.5-1.amzn2.0.2.x86_64 already installed and latest version
Nothing to do
export ACCOUNT_ID=937224085622
export AWS_REGION=us-east-1
us-east-1
Checking CDK Status
Updating CDK

up to date, audited 487 packages in 2s

39 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Installing Typescript

up to date, audited 487 packages in 2s

39 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Installing Node Modules

up to date, audited 487 packages in 2s

39 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Creating SciPy and MXNet Lambda layer artifact
Creating layer compatible with python version 3.6
Requirement already satisfied: pip in /var/lang/lib/python3.6/site-packages (21.0)
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.0
    Uninstalling pip-21.0:
      Successfully uninstalled pip-21.0
Successfully installed pip-21.3.1
Collecting scipy==1.5.2
  Downloading scipy-1.5.2-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
Collecting mxnet==1.4.0
  Downloading mxnet-1.4.0-py2.py3-none-manylinux1_x86_64.whl (29.6 MB)
Collecting numpy>=1.14.5
  Downloading numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
Collecting requests>=2.20.0
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting graphviz<0.9.0,>=0.8.1
  Downloading graphviz-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting numpy>=1.14.5
  Downloading numpy-1.14.6-cp36-cp36m-manylinux1_x86_64.whl (13.8 MB)
Collecting certifi>=2017.4.17
  Downloading certifi-2022.6.15.1-py3-none-any.whl (160 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, numpy, graphviz, scipy, mxnet
Successfully installed certifi-2022.6.15.1 charset-normalizer-2.0.12 graphviz-0.8.4 idna-3.3 mxnet-1.4.0 numpy-1.14.6 requests-2.27.1 scipy-1.5.2 urllib3-1.26.12
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Done creating layer!
-rw-r--r-- 1 root root 74M Sep 13 00:06 layer.zip
/home/ec2-user/environment/aws-serverless-for-machine-learning-inference
Deploying CDK Application
/home/ec2-user/environment/aws-serverless-for-machine-learning-inference/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
lib/batch-resources.ts:87:7 - error TS2345: Argument of type 'this' is not assignable to parameter of type 'Construct'.
  Type 'BatchResources' is not assignable to type 'Construct'.
    Types of property 'node' are incompatible.
      Type 'ConstructNode' is missing the following properties from type 'Node': _locked, _children, _context, _metadata, and 6 more.

87       this,
         ~~~~

    at createTSError (/home/ec2-user/environment/aws-serverless-for-machine-learning-inference/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/ec2-user/environment/aws-serverless-for-machine-learning-inference/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/ec2-user/environment/aws-serverless-for-machine-learning-inference/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/ec2-user/environment/aws-serverless-for-machine-learning-inference/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/ec2-user/environment/aws-serverless-for-machine-learning-inference/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .ts] (/home/ec2-user/environment/aws-serverless-for-machine-learning-inference/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19) {
  diagnosticCodes: [ 2345 ]
}

Subprocess exited with error 1

**Comment by sudosean** [comment]
+1, I'm running this locally from `install.sh` with the same error

**Comment by sudosean** [comment]
@larrygoyeau I'm pretty sure this relates to [this issue](https://github.com/aws/aws-cdk/issues/542) it seems updating package json to v2 of cdk should work. However, all the dependencies in this project have the highest version of `1.172.0` I still get this error after changing dependency versions around; here is what I"m left with:

```
{
  "dependencies": {
    "@aws-cdk/assert": "^1.172.0",
    "@aws-cdk/aws-apigateway": "^1.172.0",
    "@aws-cdk/aws-batch": "^1.172.0",
    "@aws-cdk/aws-ec2": "^1.172.0",
    "@aws-cdk/aws-ecr": "^1.172.0",
    "@aws-cdk/aws-ecr-assets": "^1.172.0",
    "@aws-cdk/aws-iam": "^1.172.0",
    "@aws-cdk/aws-lambda": "^1.172.0",
    "@aws-cdk/aws-lambda-event-sources": "^1.172.0",
    "@aws-cdk/aws-logs": "^1.172.0",
    "@aws-cdk/aws-s3": "^1.172.0",
    "@aws-cdk/aws-ssm": "^1.172.0",
    "@aws-cdk/custom-resources": "^1.172.0",
    "@types/jest": "^29.0.2",
    "@types/node": "^18.7.18",
    "cdk-ecr-deployment": "^2.5.6",
    "ts-node": "^10.9.1",
    "typescript": "^4.8.3"
  }
}
```

Edit: I noticed the dependencies are defined in `cdkmodules.txt` so I removed package.json and ran install again. This is the new error and it has to do with cdk version:

```
NOTICES

19836	AWS CDK v1 has entered maintenance mode

	Overview: AWS CDK v1 has entered maintenance mode on June 1, 2022.
	          Migrate to AWS CDK v2 to continue to get the latest features
	          and fixes!

	Affected versions: framework: 1.*, cli: 1.*

	More information at: https://github.com/aws/aws-cdk/issues/19836
```

**Comment by buissmaster** [comment]
+1 facing same issue

**Comment by medarg** [comment]
As @sudosean  mentioned, I believe these errors are possibly related to [CDK v1 entering maintenance mode after June 1, 2022  ](https://github.com/aws/aws-cdk/issues/19836). 

I have migrated the code to CDK v2 (2.59.0) and pushed the changes to the main branch. Changes successfully tested on an AWS Cloud9 m5.large. 

@buissmaster - Please let me know if this resolves the issue. 

Thank You!

**Comment by medarg** [comment]
Closing issue.  Please reopen if issue persists.  Thank you.
