### ISSUE TITLE
can't get started

### ISSUE THREAD

**Issue by InquestGeronimo** [aws-samples/aws-serverless-for-machine-learning-inference#5]
Hi recent changes were made to the directory structure and it seems that running installation via the current instructions in the readme doesn't work.

In addition, after I run ./install.sh, CLI states "Deploying CDK Application" and nothing else happens afterwards. The only thing that was created was a local image/container on my local machine's Docker. What are the next steps for getting this onto my  AWS account for real-time inference? 

In the root readme it states, `Navigate to the CloudFormation console and find the API endpoint URL (httpAPIUrl) from the stack output.` however I'm not able to find the API endpoint on my account's cloudformation. Thank you.

**Comment by medarg** [comment]
Hi @InquestGeronimo - Thank you for the feedback.  I've updated the instructions to reflect the new directory structure. 

Are you trying to follow on a local machine or AWS Cloud9?  I have just deployed and successfully tested this on a brand new AWS account from a Cloud9 instance (m5.large with resized 50G local storage volume).  Once deployed, the API endpoint URL will be displayed on the terminal.  Moreover, you can find the same info on the CloudFormation console --> `MLServerlessStack` --> Outputs tab.

**Comment by InquestGeronimo** [comment]
Thanks @medarg, Just an FYI, it wasn't clear in the README that using Cloud9 is how you leverage AWS, while using terminal flow is only for local dev. Because in the past I've used terminal to interface with AWS via AWS CLI.

**Comment by medarg** [comment]
@InquestGeronimo README specifies to run `./install.sh` if following along on a local x86 machine or `./cloud9_install.sh` if on a Cloud9 instance.  Cloud9 is the preferred way to deploy this sample code as it comes pre-installed/pre-configured with all of the required dependencies.  You can still leverage a local machine as long as the required dependencies are present and configured (NodeJs and NPM, Typescript, Docker, AWS CLI and AWS CDK).
